return {
    'nvim-telescope/telescope.nvim',
    branch = '0.1.x',
    dependencies = { 'nvim-lua/plenary.nvim' },
    keys = {
        { "<leader>bt",  function() require('telescope.builtin').buffers() end,                   desc = 'Buffers (telescope)' },
        { "<leader>fg",  function() require('telescope.builtin').git_files() end,                 desc = 'Git Files' },
        { "<leader>fr",  function() require('telescope.builtin').oldfiles() end,                  desc = 'Recent Files' },
        { "<leader>ff",  function() require('telescope.builtin').find_files() end,                desc = 'Files' },
        { "<leader>gtb", function() require('telescope.builtin').git_branches() end,              desc = 'Branches' },
        { "<leader>gtc", function() require('telescope.builtin').git_commits() end,               desc = 'Commits' },
        { "<leader>gts", function() require('telescope.builtin').git_status() end,                desc = 'Status' },
        { "<leader>gtS", function() require('telescope.builtin').git_stash() end,                 desc = 'Stash' },
        { "<leader>sb",  function() require('telescope.builtin').current_buffer_fuzzy_find() end, desc = 'Search in Buffer' },
        { "<leader>st",  function() require('telescope.builtin').live_grep() end,                 desc = 'Live Grep' },
        { "<leader>sv",  function() require('telescope.builtin').treesitter() end,                desc = 'Treesitter' },
        { "<leader>tb",  function() require('telescope.builtin').builtin() end,                   desc = 'Builtins' },
        { "<leader>tm",  function() require('telescope.builtin').marks() end,                     desc = 'Marks' },
        { "<leader>tj",  function() require('telescope.builtin').jumplist() end,                  desc = 'Jumplist' },
        { "<leader>tr",  function() require('telescope.builtin').registers() end,                 desc = 'Registers' },
        { "<leader>thc", function() require('telescope.builtin').search_history() end,            desc = "Command History" },
        { "<leader>ths", function() require('telescope.builtin').search_history() end,            desc = "Search History" },
        { "<leader>thq", function() require('telescope.builtin').quickfixhistory() end,           desc = "Quickfix History" },
        { "<leader>+c",  function() require('telescope.builtin').commands() end,                  desc = 'Commands' },
        { "<leader>+s",  function() require('telescope.builtin').colorscheme() end,               desc = 'Colorschemes' },
        { "<leader>+k",  function() require('telescope.builtin').keymaps() end,                   desc = 'Keymaps' },
        { "<leader>+h",  function() require('telescope.builtin').help_tags() end,                 desc = 'Help' },
    }
}
